
services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:5000 
    depends_on:
      - backend
    networks:
      - app-network
      

networks:
  app-network:
    driver: bridge

